export const FIELD_GROUPS: Record<string, readonly string[]> = {
  'Identity & Status': [
    'ID',
    'name_prefix',
    'name_suffix',
    'specsuffix_hidden',
    'gender',
    'gender_align',
    'pronouns',
    'birth_cooldown',
    'status',
    'backstory',
    'moons',
    'trait',
    'facets',
  ],
  Relationships: [
    'parent1',
    'parent2',
    'adoptive_parents',
    'mate',
    'previous_mates',
    'faded_offspring',
    'mentor',
    'former_mentor',
    'patrol_with_mentor',
    'current_apprentice',
    'former_apprentices',
  ],
  Appearance: [
    'tortie_enabled',
    'pelt_name',
    'pelt_color',
    'pelt_length',
    'sprite_newborn',
    'sprite_kitten',
    'sprite_adolescent',
    'sprite_adult',
    'sprite_senior',
    'sprite_para_adult',
    'reverse',
    'skin',
    'vitiligo',
    'points',
    'white_patches_tint',
    'tortie_marking',
    'tortie_base',
    'tortie_color',
    'tortie_pattern',
    'white_patches',
    'eye_colour',
    'eye_colour2',
    'tint',
    'scars',
    'accessory',
  ],
  'Skills & Progress': [
    'skill_dict',
    'experience',
    'inventory',
    'courage',
    'compassion',
    'intelligence',
    'empathy',
    'w_done',
    'talked_to',
    'flirted',
    'insulted',
    'did_activity',
  ],
  Faith: [
    'dark_forest_affinity',
    'starclan_affinity',
    'opacity',
    'faith',
    'lock_faith',
    'revives',
    'joined_df',
    'graduated_df',
    'connected_dialogue',
    'prevent_fading',
    'no_faith',
    'df_mentor',
    'df_apprentices',
    'df_patrols',
    'df_join_moon',
  ],
};

export const FIELD_LABELS: Record<string, string> = {
  ID: 'ID',
  name_prefix: 'Name prefix',
  name_suffix: 'Name suffix',
  specsuffix_hidden: 'Hide special suffix',
  gender_align: 'Gender alignment',
  birth_cooldown: 'Birth cooldown',
  'pelt_para_adult': 'Paralyzed sprite',
  no_kits: 'Cannot have kits',
  no_retire: 'Cannot retire',
  no_mates: 'Cannot have mates',
  prevent_fading: 'Prevent fading',
  df_mentor: 'Dark Forest mentor',
  df_apprentices: 'Dark Forest apprentices',
  df_join_moon: 'Dark Forest join moon',
};

export const FIELD_DESCRIPTIONS: Record<string, string> = {
  ID: 'The cat identifier used by relationships and other save data.',
  name_prefix: 'The first part of the cat\'s name.',
  name_suffix: 'The second part of the cat\'s name.',
  specsuffix_hidden: 'Whether the cat\'s special name suffix is hidden.',
  gender: 'The cat\'s gender.',
  gender_align: 'How the cat\'s gender is aligned for pronouns and relationships.',
  pronouns: 'The pronouns used for this cat.',
  birth_cooldown: 'Moons remaining before this cat can give birth again.',
  status: 'Status-specific data used by the game.',
  backstory: 'The selected backstory category for this cat.',
  backstory_str: 'The custom backstory text shown for this cat.',
  moons: 'The cat\'s age in moons.',
  trait: 'The cat\'s personality trait.',
  facets: 'The numeric facet values that refine the cat\'s trait.',
  parent1: 'The cat\'s first biological parent.',
  parent2: 'The cat\'s second biological parent.',
  adoptive_parents: 'Cats who adopted this cat.',
  mate: 'The cat\'s current mate or mates.',
  previous_mates: 'Cats who were previously mates with this cat.',
  faded_offspring: 'Offspring whose records have faded from the living clan.',
  mentor: 'The cat\'s current mentor.',
  former_mentor: 'Cats who previously mentored this cat.',
  patrol_with_mentor: 'The number of patrols this cat has taken with its mentor.',
  current_apprentice: 'The apprentice or apprentices currently assigned to this cat.',
  former_apprentices: 'Cats this cat mentored in the past.',
  tortie_enabled: 'Whether this cat uses a tortoiseshell pelt.',
  pelt_name: 'The base pelt pattern.',
  pelt_color: 'The base color of the pelt.',
  pelt_length: 'The length of the cat\'s fur.',
  sprite_newborn: 'The sprite pose used when the cat is a newborn.',
  sprite_kitten: 'The sprite pose used when the cat is a kitten.',
  sprite_adolescent: 'The sprite pose used when the cat is an adolescent.',
  sprite_adult: 'The sprite pose used when the cat is an adult.',
  sprite_senior: 'The sprite pose used when the cat is a senior.',
  sprite_para_adult: 'The sprite pose used for a paralyzed adult cat.',
  reverse: 'Whether the cat sprite faces the opposite direction.',
  skin: 'The cat\'s skin color.',
  vitiligo: 'The vitiligo marking pattern, if any.',
  points: 'The color-point marking pattern, if any.',
  white_patches_tint: 'The tint applied to the cat\'s white patches.',
  tortie_marking: 'The tortoiseshell marking style.',
  tortie_base: 'The base pelt color beneath the tortoiseshell pattern.',
  tortie_color: 'The secondary color used in the tortoiseshell pattern.',
  tortie_pattern: 'The tortoiseshell pattern layout.',
  white_patches: 'The white patch marking pattern.',
  eye_colour: 'The cat\'s primary eye color.',
  eye_colour2: 'The cat\'s secondary eye color for heterochromia.',
  tint: 'The color tint applied over the cat sprite.',
  scars: 'The scars displayed on the cat.',
  accessory: 'The accessories displayed on the cat.',
  skill_dict: 'The cat\'s skills, tiers, and interests.',
  experience: 'The cat\'s total experience points.',
  inventory: 'Items currently carried by the cat.',
  courage: 'The cat\'s courage stat.',
  compassion: 'The cat\'s compassion stat.',
  intelligence: 'The cat\'s intelligence stat.',
  empathy: 'The cat\'s empathy stat.',
  w_done: 'Whether the cat has completed its current work.',
  talked_to: 'Whether the cat has been talked to during the current cycle.',
  flirted: 'Whether the cat has flirted during the current cycle.',
  insulted: 'Whether the cat has insulted someone during the current cycle.',
  did_activity: 'Whether the cat has completed an activity during the current cycle.',
  dark_forest_affinity: 'The cat\'s affinity with the Dark Forest.',
  starclan_affinity: 'The cat\'s affinity with StarClan.',
  opacity: 'The transparency of the cat sprite.',
  faith: 'The cat\'s current faith value.',
  lock_faith: 'Whether the cat\'s faith is prevented from changing.',
  revives: 'The number of revives remaining for this cat.',
  joined_df: 'Whether the cat has joined the Dark Forest.',
  graduated_df: 'Whether the cat has graduated from Dark Forest training.',
  connected_dialogue: 'Dialogue connection data associated with this cat.',
  prevent_fading: 'Whether this cat is prevented from fading.',
  no_faith: 'Whether the cat is excluded from faith mechanics.',
  df_mentor: 'The cat\'s Dark Forest mentor.',
  df_apprentices: 'The apprentices assigned to this cat in the Dark Forest.',
  df_patrols: 'The number of Dark Forest patrols for this cat.',
  df_join_moon: 'The moon when this cat joined the Dark Forest.',
  favourite: 'Whether this cat is marked as a favorite.',
  paralyzed: 'Whether this cat is paralyzed.',
  no_kits: 'Whether this cat cannot have kits.',
  no_retire: 'Whether this cat cannot retire.',
  no_mates: 'Whether this cat cannot have mates.',
};

export const BOOL_FIELDS = new Set([
  'specsuffix_hidden',
  'reverse',
  'paralyzed',
  'no_kits',
  'no_retire',
  'no_mates',
  'prevent_fading',
  'favourite',
  'w_done',
  'talked_to',
  'insulted',
  'flirted',
  'joined_df',
  'graduated_df',
  'no_faith',
  'did_activity',
]);

export const INT_FIELDS = new Set([
  'birth_cooldown',
  'moons',
  'patrol_with_mentor',
  'experience',
  'opacity',
  'revives',
  'faith',
  'df_patrols',
  'df_join_moon',
  'dark_forest_affinity',
  'starclan_affinity',
  'courage',
  'compassion',
  'intelligence',
  'empathy',
]);

export const NULLABLE_FIELDS = new Set([
  'parent1',
  'parent2',
  'mentor',
  'eye_colour2',
  'white_patches',
  'vitiligo',
  'points',
  'white_patches_tint',
  'tortie_marking',
  'tortie_base',
  'tortie_color',
  'tortie_pattern',
  'df_mentor',
]);

export const LIST_FIELDS = new Set([
  'adoptive_parents',
  'former_mentor',
  'mate',
  'previous_mates',
  'current_apprentice',
  'former_apprentices',
  'faded_offspring',
  'df_apprentices',
  'inventory',
  'scars',
  'accessory',
]);

export const DICT_FIELDS = new Set(['status', 'pronouns', 'skill_dict', 'connected_dialogue']);

export function labelFor(key: string): string {
  return FIELD_LABELS[key] ?? key.replace(/_/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());
}

export function groupForKey(key: string): string | undefined {
  return Object.entries(FIELD_GROUPS).find(([, keys]) => keys.includes(key))?.[0];
}

export function knownKeys(): Set<string> {
  return new Set(Object.values(FIELD_GROUPS).flatMap((keys) => keys));
}

export function serializeList(text: string): string[] {
  return text.split(',').map((item) => item.trim()).filter(Boolean);
}

export function displayValue(value: unknown): string {
  if (Array.isArray(value)) return value.map((item) => String(item)).join(', ');
  return value == null ? '' : String(value);
}
